/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentaRouteImport } from './routes/venta'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as CierreRouteImport } from './routes/cierre'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VentaRoute = VentaRouteImport.update({
  id: '/venta',
  path: '/venta',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const CierreRoute = CierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cierre': typeof CierreRoute
  '/consulta': typeof ConsultaRoute
  '/cuentas': typeof CuentasRoute
  '/inventario': typeof InventarioRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cierre': typeof CierreRoute
  '/consulta': typeof ConsultaRoute
  '/cuentas': typeof CuentasRoute
  '/inventario': typeof InventarioRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cierre': typeof CierreRoute
  '/consulta': typeof ConsultaRoute
  '/cuentas': typeof CuentasRoute
  '/inventario': typeof InventarioRoute
  '/pedidos': typeof PedidosRoute
  '/venta': typeof VentaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cierre'
    | '/consulta'
    | '/cuentas'
    | '/inventario'
    | '/pedidos'
    | '/venta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cierre'
    | '/consulta'
    | '/cuentas'
    | '/inventario'
    | '/pedidos'
    | '/venta'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cierre'
    | '/consulta'
    | '/cuentas'
    | '/inventario'
    | '/pedidos'
    | '/venta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CierreRoute: typeof CierreRoute
  ConsultaRoute: typeof ConsultaRoute
  CuentasRoute: typeof CuentasRoute
  InventarioRoute: typeof InventarioRoute
  PedidosRoute: typeof PedidosRoute
  VentaRoute: typeof VentaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venta': {
      id: '/venta'
      path: '/venta'
      fullPath: '/venta'
      preLoaderRoute: typeof VentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cierre': {
      id: '/cierre'
      path: '/cierre'
      fullPath: '/cierre'
      preLoaderRoute: typeof CierreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CierreRoute: CierreRoute,
  ConsultaRoute: ConsultaRoute,
  CuentasRoute: CuentasRoute,
  InventarioRoute: InventarioRoute,
  PedidosRoute: PedidosRoute,
  VentaRoute: VentaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
